 g++ -g MLP.cpp matrix.cpp -o mlp_program



# g++ -std=c++17 mlp_test.cpp matrix.cpp MLP.cpp -o run_tests \
    -lgtest -lgtest_main -pthread
#g++ -std=c++17 -DUNIT_TESTING MLPTest.cpp matrix.cpp MLP.cpp -o run_tests -lgtest -lgtest_main -pthread