#MLP
 g++ -g MLP.cpp matrix.cpp -o mlp_program



#MLPTEST
g++ -std=c++17 -DUNIT_TESTING MLPTest.cpp matrix.cpp MLP.cpp -o run_tests -lgtest -lgtest_main -pthread


#image processor
g++ -std=c++17 image_processor.cpp -o output `pkg-config --cflags --libs opencv4`